-- CALCULATED PRESSURES AND RATES
-- well bottom hole pressure for all wells
WBHP
/

-- well WCUT
WWCT
/

-- well oil rate
WOPR
/

-- well oil rate total
WOPT
/

WWIR
/
--well water rate
WWPR
/
--well liquid rate
WLPR
/
FGPR

-- field oil production rate
FOPR

-- field water production rate
FWPR

-- field gas production rate
--FGPR

-- field water cut
FWCT

-- field water injection rate
FWIR

--liquid and res volume production rates
FLPR
FVPR

-- CALCULATED FIELD PRESSURES AND TOTAL PRODUCTION
-- Field average pressure
FPR

-- Field oil production total
FOPT

-- Field oil in place
FOIP

-- Field recovery efficiency
FOE

-- Field water production total
FWPT

-- Field water injection total
FWIT

-- Field water in place
FWIP


